using System.Collections;
using System.Collections.Generic;
using UnityEngine;


public class MainCamera : MonoBehaviour
{
    private Transform target;      // O objeto que a cï¿½mera segue (alvo)
    public Collider2D area;         // A regiï¿½o em que a cï¿½mera estï¿½
    public float SpeedFactor = 3f;  // A Velocidade de aproximaï¿½ï¿½o da cï¿½mera
    public bool smoothMovement;
    public bool FreeCam;
    public bool Freeze;

    private Camera m_Camera;        // Acesso ao script Camera
    private float aspectRatioOffsetX;// Compensaï¿½ï¿½o ao tamanho horizontal da camera ao depender do formato da tela
    private float aspectRatioOffsetY;// Compensaï¿½ï¿½o 
    public float aspectRatio;       // Proporï¿½ï¿½es da camera
    private const float zPos = -10; // A posiï¿½ï¿½o padrï¿½o da cï¿½mera no eixo Z

    public static MainCamera Instance  // Propriedade estï¿½tica para facilitar o acesso da cï¿½mera por outros scripts (singleton)
    {
        get
        {
            return FindObjectOfType<MainCamera>();
        }
    }

    // Start is called before the first frame update
    void Start()
    {
        m_Camera = GetComponent<Camera>();
        target = PlayerControl.Instance.transform;
        if(target == null){
            Debug.LogError("Player not found - Bubble Manager");
        }

        // Usamos o tamanho vertical da camera e as dimensï¿½es da tela para calcular o tamanho horizontal
        aspectRatio = ((float)Screen.width) / ((float)Screen.height);
        aspectRatioOffsetX = aspectRatio * m_Camera.orthographicSize;
        aspectRatioOffsetY = m_Camera.orthographicSize;
        BGCamera.Instance.ApplyAspectRatio(aspectRatio);

        // Iniciaremos a posiï¿½ï¿½o da cï¿½mera ï¿½ mesma posiï¿½ï¿½o do jogador
        transform.position = new Vector3(target.position.x, target.position.y, zPos);
    }

    // Update is called once per frame
    void Update()
    {
        if (Freeze) return;
        Vector2 newPos;

        newPos = target.position; // Posiï¿½ï¿½o desejada (posiï¿½ï¿½o do jogador/alvo)

       
        if (!FreeCam)
        {
            if(area.bounds.size.x < aspectRatioOffsetX * 2) newPos = new Vector2(area.transform.position.x + area.offset.x, newPos.y);
            if(area.bounds.size.y < aspectRatioOffsetY * 2) newPos = new Vector2(newPos.x, area.transform.position.y + area.offset.y);

            if (area != null)
            {
                /*
                  Essa parte ï¿½ o que impede a camera de sair das ï¿½reas de cada sala
                  Cada uma dessas condiï¿½ï¿½es garante que a camera nï¿½o passe das bordas esquerda, direita, superior e inferior

                  Para isso verificamos se a borda da cï¿½mera (newPos.x|y +/- [Tamanho da Camera]) nï¿½o estï¿½ alï¿½m da borda oposta da tela (area.bounds.center.x|y +/- area.bounds.extents.x|y)

                  Para as bordas verticais, podemos verificar o tamanho da cï¿½mera usando a propriedade ortographicSize
                  Porï¿½m, para as horizontais, devemos levar em consideraï¿½ï¿½o o formato da tela do usuï¿½rio. Fizemos esse cï¿½lculo em start()
                 */

                if (newPos.x - aspectRatioOffsetX < area.bounds.center.x - area.bounds.extents.x)                // ESQUERDA
                {
                    newPos.x = (area.bounds.center.x - area.bounds.extents.x) + aspectRatioOffsetX;
                }
                else if (newPos.x + aspectRatioOffsetX > area.bounds.center.x + area.bounds.extents.x)           // DIREITA
                {
                    newPos.x = (area.bounds.center.x + area.bounds.extents.x) - aspectRatioOffsetX;
                }

                if (newPos.y - aspectRatioOffsetY < area.bounds.center.y - area.bounds.extents.y)        // SUPERIOR
                {
                    newPos.y = (area.bounds.center.y - area.bounds.extents.y) + aspectRatioOffsetY;
                }
                else if (newPos.y + aspectRatioOffsetY > area.bounds.center.y + area.bounds.extents.y)   // INFERIOR
                {
                    newPos.y = (area.bounds.center.y + area.bounds.extents.y) - aspectRatioOffsetY;
                }
            }

            Vector2 distance = newPos - (Vector2)transform.position; // Distancia entre a posiï¿½ï¿½o final e a posiï¿½ï¿½o atual

            if (!smoothMovement)
            {
                transform.position = newPos; // Caso a cï¿½mera ja esteja perto da personagem, pulamos diretamente ï¿½ ela
            }
            else
            {
                transform.position += (Vector3)distance * ((float)-1.957 * (Mathf.Pow(0.6f, Time.deltaTime) - 1)) * SpeedFactor;
                /* Caso contrï¿½rio, aproxima a cï¿½mera da personagem de forma exponencial
                 Movimento desejado ï¿½  transform.position += distance * 0.6
                 Porï¿½m ao levar em consideraï¿½ï¿½o deltaTime, a fï¿½rmula que corretamente aproxima esse movimento ï¿½  distance * -1.957 * (0.6^deltaTime - 1)
                 Fï¿½rmula obtida atravï¿½s da integral definida de 0.6^x entre 0 e deltaTime
                */
            }
        }
        else
        {
            transform.position = newPos;
        }
        transform.position = new Vector3(transform.position.x, transform.position.y, zPos); // Mantemos a posiï¿½ï¿½o Z da Cï¿½mera no valor padrï¿½o
    }

    public void ChangeArea(GameObject newArea)  // Mudanï¿½a de ï¿½rea da cï¿½mera
    {
        area = newArea.GetComponent<Collider2D>();
        FreeCam = false;
        StartCoroutine(ChangeCameraSize(area.GetComponent<ScreenZone>().cameraSize)); // Utilizamos o tamanho de cï¿½mera especificado pela ï¿½rea
    }

    IEnumerator ChangeCameraSize(float targetSize)      // Mudamos o tamanho da cï¿½mera Gradualmente
    {
        smoothMovement = true;
        float t = 0;
        var oldSize = m_Camera.orthographicSize;

        aspectRatioOffsetX = (((float)Screen.width) / ((float)Screen.height)) * targetSize;
        aspectRatioOffsetY = targetSize;

        while (t < 1)
        {
            m_Camera.orthographicSize = Mathf.Lerp(oldSize, targetSize, t);
            t += 5 * Time.deltaTime;
            yield return null;
        }
        m_Camera.orthographicSize = targetSize;
        // Usamos o tamanho vertical da camera e as dimensï¿½es da tela para calcular o tamanho horizontal



        var i = 15;
        while (i > 0)
        {
            i--;
            yield return new WaitForFixedUpdate();
        }

        smoothMovement = false;
    }
}
